# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_combn_sum <- function(vals, n, n_k) {
    .Call(`_ClusROC_fast_combn_sum`, vals, n, n_k)
}

